name: skullface.me | Design Babe
title: skullface.me | Design Babe
email: meow@skullface.me
author: skullface
description: I’m an interdisciplinary designer, developer, and illustrator (Design Babe) dual-wielding compassion + cuteness in the Midwest.
baseurl:  "" # the subpath of your site, e.g. /blog
url:      "http://skullface.me" # the base hostname & protocol for your site

logo:         assets/img/mock.jpg
locale:       en-US
lang:         en-US
encoding:     "utf-8"

author:
  facebook:   skvllface
  twitter:    skullface

twitter:
  username:   skullface

# Build setings
markdown:     kramdown
highlighter:  rouge
permalink:    /:year/:title
future:       false

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script
  - node_modules
  - package.json
  - webpack.config.js
  - vendor
  - "*.lock"
  - "*.log"
   
# Sass
sass:
  style: :compressed
  sass_dir: assets/css
  load_paths:
    - node_modules/

# Custom variables
mediapath:
  post: media/posts/

# Collections
collections:
  sketches:
    output: true
    permalink: /sketchbook/:path/
  projects:
    output: true
    permalink: /project/:path/
  products:
    output: true
    permalink: /shop/:path/

# Defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
